### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by punto1**
removed version bin Beaker < 1.7 (caused a downgrade in Beaker version upon installment)

### CODE REVIEW

**Comment by aspyatkin** [comment]
@punto1 thanks

**Comment by gberaudo** [comment]
I am using python 3.5 and was hit by this already corrected issue: `pkg_resources.VersionConflict: (Beaker 1.8.0 (/usr/local/python/lib/python3.5/site-packages), Requirement.parse('Beaker<1.7,>=1.6.4'))`.

@aspyatkin, have you considered publishing a release?

**Comment by aspyatkin** [comment]
@gberaudo Thank you for pointing that out. Unfortunately, at present I don't have an opportunity to test it against Python 3.5 and Beaker 1.8. Nevertheless, I've published a [release](https://pypi.python.org/pypi/beakeredis/0.1.0), so I kindly ask you to let me know if it works well.

**UPD:** I've  updated Travis CI config as well as some tests, and it looks like it should work with Python 3.5.

**Comment by gberaudo** [comment]
It works great, thanks @aspyatkin.

**Pull request merged**
